### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by frank1789** [bazelbuild/vscode-bazel#104]
- Issue Type: `Performance`
- Extension Name: `vscode-bazel`
- Extension Version: `0.1.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/francesco/BazelBuild.vscode-bazel-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by allevato** [comment]
Can you upload the log that you're referencing in the issue?

This may have been fixed by #89 which will be in the next release, but without the log it's hard to say for sure.

**Comment by allevato** [comment]
Can you check this again with the latest release (0.2.0) of the extension on the marketplace? We fixed a couple issues that may have been causing this.

**Comment by frank1789** [comment]
Solved!
