### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by muendelezaji** [bazelbuild/vscode-bazel#105]
- Issue Type: `Performance`
- Extension Name: `vscode-bazel`
- Extension Version: `0.1.0`
- OS Version: `Linux x64 4.13.0-32-generic`
- VSCode version: `1.33.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

Hi, I see there is a related issue #104 which might have been fixed in #89 (log file attached). Is there a way to quickly apply it to my workspace aside from waiting for a new release?

[BazelBuild.vscode-bazel-unresponsive.cpuprofile.txt](https://github.com/bazelbuild/vscode-bazel/files/3107939/BazelBuild.vscode-bazel-unresponsive.cpuprofile.txt)

**Comment by allevato** [comment]
Can you check this again with the latest release (0.2.0) of the extension on the marketplace? We fixed a couple issues that may have been causing this.

**Comment by muendelezaji** [comment]
Seems to be fixed. Thanks 👍
