### ISSUE TITLE
Classpath incomplete warning with vscode-java

### ISSUE THREAD

**Issue by tarr11** [bazelbuild/vscode-bazel#106]
When using vscode-bazel with vscode-java, I receive a "Classpath is incomplete" warning.

https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning

It appears that vscode-java can't recognize bazel BUILD files.

**Comment by thomasvl** [comment]
Now sure I follow, what's the issue on this project then?

**Comment by tarr11** [comment]
Yeah, I guess this is a bug for vscode-java.

**Comment by jamesbroadhead** [comment]
This is redhat-developer/vscode-java#909
