### ISSUE TITLE
Constant loading, blocks all other operations

### ISSUE THREAD

**Issue by strican** [bazelbuild/vscode-bazel#109]
Working in a lerna-based Typescript repo, I get the clock symbol when I open the folder in VSCode. The extension seems to be searching and hanging. Version control stops updating, too. Note that I do have a subdirectory that is bazel-based. Still, the list of bazel targets never loads either. Disabling the extension and reloading causes everything to work fine.

**Comment by allevato** [comment]
Can you check this again with the latest release (0.2.0) of the extension on the marketplace? We fixed a couple issues that may have been causing this.

**Comment by strican** [comment]
I don't appear to be seeing this anymore, so this appears to be fixed. Thanks for following up.
