### ISSUE TITLE
Cut a (bugfix) release?

### ISSUE THREAD

**Issue by whilp** [bazelbuild/vscode-bazel#129]
There have been some fixes as well as a few improvements since the last release in May:

1. https://github.com/bazelbuild/vscode-bazel/pull/126 (selfishly)
2. https://github.com/bazelbuild/vscode-bazel/pull/118
3. https://github.com/bazelbuild/vscode-bazel/pull/117

When is the next release planned? Anything I can do to help make it happen? Thank you!

**Comment by allevato** [comment]
Yes, it's been too long since we've cut a release. I'll look into it by the end of the week.

**Comment by whilp** [comment]
Right on, thank you!

**Comment by allevato** [comment]
The 0.3.0 release is now live on the Marketplace and on the GitHub releases page.
