### ISSUE TITLE
CodeLensProvider and TargetSymbolProvider are spammy for non Bazel Workspaces

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/vscode-bazel#136]
If you open a `BUILD` or `BUILD.bazel` file that isn't in a bazel workspace, both providers put up info warnings that since the file isn't in a workspace, they can't provide support.  And this just keeps happening when the re-trigger on other files, etc.

While the info is sorta useful to explain why functionality isn't provide, it quickly gets annoying also.  Does it make sense to have some way to just shut them off?  Or should we just drop the messages?

**Comment by allevato** [comment]
We should probably just drop the messages if the file isn't in a workspace.

This is analogous to opening any source file for an arbitrarily selected language in an IDE that supports that language, but where the file isn't in the current (or any) project. Most IDEs don't complain that you won't get autocomplete or indexing, you just get the reduced feature set and I think most users accept and expect that.
