### ISSUE TITLE
activation of 0.0.1 release failed

### ISSUE THREAD

**Issue by avibryant** [bazelbuild/vscode-bazel#14]
I downloaded the recent release and installed it into VS Code 1.29.1 running on Mac OS 10.13.6.

The developer tools show the following error:
Activating extension 'BazelBuild.vscode-bazel' failed: Cannot find module 'xml2js'

**Comment by smukherj1** [comment]
Did you run "npm install"? in the extension directory?

**Comment by allevato** [comment]
By "downloaded the recent release", do you mean from the VS Code Marketplace?

I just filed #15 and it looks like I'm seeing the same error you reported here, so it looks like they're the same issue.

**Comment by avibryant** [comment]
I downloaded https://github.com/bazelbuild/vscode-bazel/releases/download/0.0.1/vscode-bazel-0.0.1.vsix and installed it via the "Install from VSIX..." option

**Comment by allevato** [comment]
I've found the problem—some of the Node.js dependencies the extension needs at runtime were listed under `devDependencies` instead. (Rookie Node.js mistake on my part!)

I'll have a fix and a new release out shortly.

**Comment by avibryant** [comment]
This got further and I think the error I am now hitting may be related to my specific WORKSPACE, so I think we can close this issue now. Thanks!
