### ISSUE TITLE
Update linter configs

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/vscode-bazel#151]
With the two suggested extension open, an alert pops up from Prettier saying:

> You have legacy linter options in your VS Code settings. They are no longer being used. See [documentation for migration information](pointing to https://github.com/prettier/prettier-vscode#linter-integration). Would you like to remove them or view the logs?

**Comment by thomasvl** [comment]
The alert includes a button to remove the "old" settings, but it doesn't add any new ones.

**Comment by thomasvl** [comment]
A quick attempt to update things on my part results in a bunch of files being changed (and needing to make more config files).  So I'm not sure how things should eventually look.  Also, just using the current extensions/libs seems to want to reformat some of the files, so it seems the formatters have already evolved from the current state of things.

**Comment by elklein** [comment]
Yeah, I was hitting the same thing with trying to get a pull request ready. I'll probably just find a way to revert some of the "bad" formatting edits made by prettier, but it would be nice to know what others are doing for submissions here.

**Comment by vogelsgesang** [comment]
Closing this, give  that the linter& formatter were updated multiple times in the meantime and I didn't see any issues around this for a while
