### ISSUE TITLE
Build/Test Package in "BAZEL BUILD TARGETS" only works for the last package

### ISSUE THREAD

**Issue by chiahsing** [bazelbuild/vscode-bazel#165]
When I right-click on a package in BAZEL BUILD TARGETS in Explorer, and select Build Package or Test Package, it only works for the package listed at the end. For all other packages (e.g. //pdfbox), terminal shows:

```
:all' <ting task: bazel 'build' '//pdfbox

': package names may contain A-Z, a-z, 0-9, or any of ' !"#$%&'()*+,-./;<=>?[]^_`{|}~' (most 7-bit ascii characters except 0-31, 127, ':', or '\')
WARNING: Target pattern parsing failed.
': package names may contain A-Z, a-z, 0-9, or any of ' !"#$%&'()*+,-./;<=>?[]^_`{|}~' (most 7-bit ascii characters except 0-31, 127, ':', or '\')
INFO: Elapsed time: 0.128s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
The terminal process terminated with exit code: 1
```

It looks like there is a \r inserted to the package name wrongly right before ':all'. (This is under Windows 10).
If I rename it to zzpdfbox to move it to the end, it works again:

```
> Executing task: bazel 'build' '//zzpdfbox:all' <

INFO: Analyzed 4 targets (0 packages loaded, 8 targets configured).
INFO: Found 4 targets...
INFO: Elapsed time: 0.219s, Critical Path: 0.03s
INFO: 1 process: 1 worker.
INFO: Build completed successfully, 5 total actions

Terminal will be reused by tasks, press any key to close it.

```
But the second last one which used to work before renaming now stops working.

**Comment by thomasvl** [comment]
Are you on windows?

**Comment by chiahsing** [comment]
Yes

**Comment by thomasvl** [comment]
Then #153 was likely the same issue.  It should be fixed on master, but a release hasn't been done yet.

**Comment by thomasvl** [comment]
Maybe not #153 directly, but #158 in general might have gotten things.

**Comment by vogelsgesang** [comment]
This seems to be fixed and the fix is also already part of all recent releases.

Please reopen, in case this turns out to still be an issue
