### ISSUE TITLE
Need a readme how to build the plugin

### ISSUE THREAD

**Issue by konste** [bazelbuild/vscode-bazel#168]
Last published release of the plugin is vscode-bazel 0.3.0 which seems to be rather old. I would like to build the latest from master and try if it fixes my problem with the debugger not stopping on the breakpoints, but I cannot figure out how to build from sources. Is it possible to extend CONTRIBUTING.md with a little Getting Started how to build it and load to vscode? I see scripts\build.sh, but apparently some preparation needs to be done before it can run.

**Comment by konste** [comment]
Thank you, @allevato !

**Comment by allevato** [comment]
@thomasvl deserves the credit, I just clicked the Merge button 🙂
