### ISSUE TITLE
buildifier not found

### ISSUE THREAD

**Issue by WesleyYue** [bazelbuild/vscode-bazel#172]
Hi, for some reason my vscode-bazel extension is unable to find buildifier on the path. It gives me the following error:
`Error: Command failed: buildifier --mode=fix --type=build --lint=fix /bin/sh: 1: buildifier: not found`

I've verified that it is indeed in my path, and I get a result from `which buildifier` as well as `buildifier -v` on the terminal.

I've found that when I provide the full path to the executable with the result from `which buildifier`, the extension works.

I found a related issue [here](https://github.com/bazelbuild/vscode-bazel/issues/70#issuecomment-492365111) but no resolution.

**Comment by thomasvl** [comment]
This likely comes down to where it is on your `PATH`, how you set your `PATH`, and how you launch vscode.  i.e. - the `PATH` vscode is getting might not have your changes applied.  This is likely going to be somewhat specific to your setup, so without more info, it will be hard for others to help suggested things.  Start by looking at where/how you modify your `PATH` and how you launch vsCode.

**Comment by WesleyYue** [comment]
Ah that is indeed the issue. I add to my path for Go binaries in ~/.bashrc which my vscode instance doesn't have access to when launching from my launcher. I tried launching vscode in my terminal and it was able to find buildifier.

Thanks for your help.

**Comment by samuela** [comment]
Is there a way to customize where the extension looks for the buildifier binary? I'm in a similar boat, and running over SSH which makes it a bit tricky to set VSCode's PATH.

**Comment by monajalal** [comment]
I get the same error in VSCODE

```
Buildifier was not found; linting and formatting of Bazel files will not be available. Please download it from https://github.com/bazelbuild/buildtools/releases and install it on your system PATH or set its location in Settings.
```

**Comment by vogelsgesang** [comment]
Did you set `bazel.buildifierExecutable`?
