### ISSUE TITLE
vscode-bazel has un-awaited promises

### ISSUE THREAD

**Issue by JayBazuzi** [bazelbuild/vscode-bazel#173]
Consider adding this lint rule in tslint.json:

```
        "no-floating-promises": true,
```

And fix the half-dozen violations.

**Comment by thomasvl** [comment]
Showing my ignorance - just adding it to `tslint.json` seems to not work, `npm run check-lint` reports:

```
Warning: The 'no-floating-promises' rule requires type information.
```
