### ISSUE TITLE
getBazelInfo() gets confused by Windows paths

### ISSUE THREAD

**Issue by JayBazuzi** [bazelbuild/vscode-bazel#176]
This line:

```
              const [key, value] = line.split(":", 2);
```

Will fail on Windows because paths have a `:` in them.

```
>bazel info
bazel-bin: C:/users/[REDACTED]/bazel-out/x64_windows-dbg/bin
```

**Comment by allevato** [comment]
I was confused at how this could possibly be the case, until I noticed this sentence in Mozilla's [documentation of `String.split`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split):

> Any leftover text is not included in the array at all.

I cannot imagine any scenario where that's the behavior I would expect or want. 🤢  I'm happy to review a small PR that does the right thing here.

**Comment by JayBazuzi** [comment]
Still working on the CLA before I can send a PR.

One option is to use `.indexOf()` and `.substring()` instead of `.split()`.

**Comment by allevato** [comment]
Yeah, or `.split(/:(.+)/)` to take advantage of capture group behavior and ignore the last element of the array that will always be an empty string. I don't have a strong opinion here about which is better stylistically, except that this is terrible. 😕 

`indexOf/substring` is probably clearer than a magic regex split.

**Comment by JayBazuzi** [comment]
I see it's also possible to skip parsing entirely by running `bazel info execution_root`, etc., but that that would require some other changes.

**Comment by thomasvl** [comment]
While not pretty, what about just doing –

```typescript
const parts = line.split(':');
const key = parts[0];
const value = parts.slice(1).join(':');
```

**Comment by allevato** [comment]
> I see it's also possible to skip parsing entirely by running `bazel info execution_root`, etc., but that that would require some other changes.

We need multiple values from the `bazel info` output, and querying them individually would require spawning multiple Bazel processes. That's extremely wasteful vs. just fixing the string parsing problem.

**Comment by thomasvl** [comment]
@JayBazuzi were you opening a PR for this?

**Comment by JayBazuzi** [comment]
Not at this time.
