### ISSUE TITLE
Likely missing targets tagged `manual`

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/vscode-bazel#181]
To collect targets for the treeview and quickpicks we use queries with `:*` and '/...`, so according to [bazel conventions](https://docs.bazel.build/versions/master/be/common-definitions.html#common.tags), they won't get included.  But given they have to be manually used by developers, they probably want to be able to use them in the extension UI.

**Comment by thomasvl** [comment]
Note: using `manual` can also be done as an implementation detail of a macro that has to make _helper_ targets, so blinding picking them up might also not be right.

**Comment by allevato** [comment]
I don't think this is a concern—targets tagged `manual` are still returned in a Bazel _query_ using a wildcard pattern (I just tested it), they're just ignored during build/test commands. So we should still be picking them up in our tree.
