### ISSUE TITLE
[windows] buildifier not found warning but it is working

### ISSUE THREAD

**Issue by limdor** [bazelbuild/vscode-bazel#183]
vscode is showing the warning that buildifier has not been found but if you try to format it is still working.
I did not have buildifier on the path, just on the plugin settings.
![image](https://user-images.githubusercontent.com/3073717/74081355-5b6d0f80-4a4e-11ea-8153-e908e90c7283.png)
![image](https://user-images.githubusercontent.com/3073717/74081388-d0404980-4a4e-11ea-83f2-dcec8ec0359d.png)
Steps to reproduce:
- Install vscode
- Install vscode-bazel extension
- Set the absolute path to buildifier.exe
- Restart vscode (The warning will appear)
- Try to format a BUILD file (It works even though the warning appears)

vscode version: 1.42.0
buildifier version: 0.29
vscode-bazel version: 0.3.0

**Comment by thomasvl** [comment]
Does it repeat if you remove the quotes from the setting?

**Comment by limdor** [comment]
If I remove the quotes it works and does not display the warning anymore.
I also tried what happens if I put the buildifier.exe into a folder with spaces, then the only way that it works is adding the quotes but the warning appears. In the case of a folder with spaces does not work without quotes.

**Comment by thomasvl** [comment]
As far as directories with spaces, that should be fixed on head. (#158)

**Comment by cameron-martin** [comment]
@limdor is this issue fixed now?

**Comment by cameron-martin** [comment]
Glad to hear this works now. I'm of the opinion that getting shell quoting involved is unnecessary here, and so working with quotes is unintended. I'll close this since we're in agreement.
