### ISSUE TITLE
[Feature request] Add option to disable CodeLens in BUILD files

### ISSUE THREAD

**Issue by ivanmilov** [bazelbuild/vscode-bazel#187]
By default in BUILD file we have CodeLen(s) on top of every target. Sometime it is useful but I want to have an option to disable it. 
This [commit](https://github.com/ivanmilov/vscode-bazel/commit/ff226ab369ca25896d32274901249f701f07c1ab) is an example how to add this option. 
Would you be so kind to implement it in the next release?

**Comment by zsh-89** [comment]
+1
Totally agree. This is very intrusive feature when editing the bazel file source code, I uninstalled the plugin itself because this feature is way too instrusive.

**Comment by ivanmilov** [comment]
> I uninstalled the plugin itself because this feature is way too instrusive.
you can just add `return [];` to provideCodeLenses() function :)

**Comment by allevato** [comment]
Having used it for a while in my own projects, I'm inclined to agree. CodeLens isn't the right UI for this, especially when there a large number of targets can appear on a single source line in a BUILD file (i.e., a macro defines multiple targets).

VS Code's "Code Actions" might be a better way of exposing them, but that also feels like it might be stretching the definition of that feature a bit. Code Actions seem to be intended more for things like "quick fixes" that refactor or transform the code, and I'd want to make sure that we leave room to support those (e.g., buildozer-based refactoring of BUILD files could be powerful). Are there examples of well-known and popular extensions that use Code Actions for this kind of "take an action on something in the file, but not edit it" pattern?

I'm also open to other suggestions for ways to integrate this.

**Comment by ivanmilov** [comment]
Great, thank you!

**Comment by jxramos** [comment]
To @allevato 's point when you do have a macro that expands to several targets the UI gets unwieldy and the text goes way out of view where it's not really usable apart from an extreme zooming out of the editor. I'm not sure what a great alternative would look like, maybe even just writing one target per line, perhaps with a collapsible of some kind where if one wished to view the codelens links they could drill into it.

I have actually found the codelens traces above macros to be a strong signal that I haven't managed to fumble the syntax or break the BUILD file in some way as I'm actively editing it. It's an immediate signal I use to let me know I need to fix something before executing a build or test.
