### ISSUE TITLE
Running build target fails with fish shell

### ISSUE THREAD

**Issue by enriched** [bazelbuild/vscode-bazel#20]
With the default shell set to [fish](https://fishshell.com) building targets from the `BAZEL BUILD TARGETS` tree does not work.  The `&&` characters that are used in the terminal command `cd <package directory> && bazel build <target>` are not valid in the fish shell. Fish uses the syntax `cd <package directory>; and bazel build <target>`.

**Comment by allevato** [comment]
For commands executed in a terminal environment, we should probably just wrap them in `bash` to make sure we don't have hidden assumptions about the user's configured shell.

**Comment by thomasvl** [comment]
Or just split it, can you likely do the `cd` and then do the `bazel` command afterward.  If someone wants to use windows, that likely would make it work there also?

**Comment by allevato** [comment]
That would also work, though one benefit of being able to chain the commands is not trying to execute `bazel` in the (admittedly rare) case that the `cd` fails. Not sure if that's worth fretting about too much.

Interestingly Windows should also work today with the `&&` syntax; it's just `fish` that seems to be problematic. But yeah, wrapping the command in `bash` would cause problems on Windows unless they had the WSL installed, I believe (not a Windows user).

**Comment by thomasvl** [comment]
Looked like when you create the terminal you can control what shell is used, but that seemed like it would be an issue for windows.  I guess that could platform check and only set the shell to bash or non windows?

**Comment by allevato** [comment]
Hmm, that seems like possibly the most reasonable approach.

Though, digging a bit further, it looks like Powershell also doesn't support `&&`; I'm not familiar enough with Windows shells and defaults to know whether that would pose an issue for the extension there.

Maybe we do the platform check and use `cmd.exe` if Windows and `bash` if anything else?

**Comment by baslas** [comment]
I can confirm it does not work on Windows with Powershell as the default terminal:
```
At line:1 char:6
+ cd . && bazel build //main:hello-world
+      ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
```
It seems this would be a valid equivalent for Powershell:
`cd .; if($?) { bazel build //main:hello-world }`

where `$?` is the [status of the last operation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-5.1#section-1).

**Comment by allevato** [comment]
We've talked a little bit more about this and it's possible that this bug goes away when we look at migrating the build/test actions to the task APIs (#7), because we'll be setting the CWD through a different method than chaining commands. If that works, it's better than us trying to replicate cross-platform shell logic ourselves.

**Comment by allevato** [comment]
The next release should fix this; I tested it by installing `fish` and making it the default shell for VS Code's integrated terminal. Launching Bazel as a task eliminates the need for us to run the command as `cd && bazel`.
