### ISSUE TITLE
Does not recognize WORKSPACE.bazel file.

### ISSUE THREAD

**Issue by logicor-cn** [bazelbuild/vscode-bazel#201]
Version 0.3.0 (September 19, 2019)

Keeps popping up error message:

"Bazel BUILD CodeLens unavailable as currently opened file is not in a Bazel workspace."

in a workspace defined by `WORKSPACE.bazel` instead of `WORKSAPCE` file.

`WORKSPACE.bazel` is also legitimate definition workspace definition file according to https://docs.bazel.build/versions/master/build-ref.html.

**Comment by technoir42** [comment]
This was fixed by #169. @allevato it's been a while since 0.3.0, could you release a new version please?

**Comment by UebelAndre** [comment]
I too would like a new version released. What does the release cadence for this plugin look like?

**Comment by logicor-cn** [comment]
Any chance we get a new release version anytime soon?

**Comment by laurentlb** [comment]
Please see or ping https://github.com/bazelbuild/vscode-bazel/issues/197

I'm closing this bug.
