### ISSUE TITLE
Is there "Bazel: Run Target"  command?

### ISSUE THREAD

**Issue by peter197321** [bazelbuild/vscode-bazel#205]
Is there a **run** command for `bazel run //main:hello-world` within vscode-bazel extension?

![image](https://user-images.githubusercontent.com/46971586/84940303-ee464680-b0df-11ea-9c3e-480d1426ef41.png)

**Comment by thinlizzy** [comment]
+1 !
a bazel run command would be really useful

**Comment by vogelsgesang** [comment]
implemented in #299
