### ISSUE TITLE
Extension provides target/package completion for BUILD files

### ISSUE THREAD

**Issue by alexfrasson** [bazelbuild/vscode-bazel#210]
### Feature Request
Enable Intellisense code completion for targets/packages within BUILD files.

https://github.com/bazelbuild/vscode-bazel/pull/209 contains a draft on how that could be done. This is the first time I write something for a vscode extension, so there might be a lot of room for improvement.

**Comment by alexfrasson** [comment]
It would be really cool if I could get some feedback regarding this feature. Would you guys be willing to support this? If so, could you have a look at the pull-request that I've submitted to see if the implementation is going in the right direction? I'm not a type/javascript nor a vscode extension developer, so I could really use another pair of eyes.

**Comment by cpsauer** [comment]
@philwo, thoughts on closing this?

Happened to run back across it and remembered your merging in the changes in #209, above. That and (probably) #1 captures the remaining spirit better.

Would have tagged @coeuvre as the other owner who might be able to close things, but it seems like he's deleted his GitHub?

**Comment by laurentlb** [comment]
I can close it :)

**Comment by philwo** [comment]
Thank you! 😊 @coeuvre should hopefully be back soon - his GitHub account was temporarily suspended for unknown reasons and we're still working with the support to get it unblocked again.

**Comment by cpsauer** [comment]
😮 
that's terrible! So sorry to hear, and the best of luck getting it back
