### ISSUE TITLE
Error when "Build Target (with Debugging)" commands are invoked from command palette

### ISSUE THREAD

**Issue by allevato** [bazelbuild/vscode-bazel#23]
The commands work from the tree view (because they are passed the arguments they need) but if invoked from the command palette, they don't have an argument and they error out.

According to https://github.com/Microsoft/vscode/issues/45119, that's expected and we need to handle the case of the command being invoked in a different context. In our case, we should detect whether there's no argument and pop up an alternative UI, like a quick-pick list to let the user type/select the target name.

**Comment by smukherj1** [comment]
I'm already working on QuickPick for our commands. I did discover this issue and my PR will fix it
