### ISSUE TITLE
Breakpoints may or may not fire depending on the form of `load()` being used

### ISSUE THREAD

**Issue by allevato** [bazelbuild/vscode-bazel#24]
This affects debugging of `.bzl` files that are in the same repository as the target being built.

Let's imagine we have a workspace named `foo` that contains `bar.bzl`, and we want to place a breakpoint in that file. Under Bazel's `execroot`, there will be a symlink `foo` to the actual directory where the workspace exists (let's call it `$HOME/Scratch/foo`), and `bar.bzl` will be in there as expected.

Likewise, files referenced from external repository references are under Bazel's `external` directory (relative to `output_base`). _This includes "external-looking" references to the **same** workspace._ So in our case, if we refer to `@foo//:bar.bzl`, then that shows up as a symlink in `.../external/foo/bar.bzl` that points to the original file.

The problem is, the source location that Bazel tests in the debug server to decide whether a breakpoint should fire differs depending on how the file was `load`ed.

For example, if I do the following:

```
load("@foo//:bar.bzl", ...)
```

Then Bazel asks "is there a breakpoint at `/private/var/tmp/_bazel_allevato/<HASH>/external/foo/bar.bzl`?" This is the form of breakpoint that we send to the debug server [today](https://github.com/bazelbuild/vscode-bazel/blob/master/src/debug-adapter/client.ts#L212-L226). (The reason I implemented this one is because it just happened to work with the repository I was testing against, which references its own `.bzl` files using the repo name.)

However, if I do the following:

```
load("//:bar.bzl", ...)
```

Then Bazel asks "is there a breakpoint at `$HOME/Scratch/foo/bar.bzl`?" In this case, it appears that it's resolving the `execroot/foo` symlink and then looking relative to that location.

Even though these are _the same file_, Bazel's path comparison sees them as being different, and a breakpoint set for one won't fire for the other.

The only way I can see around this for now is for us to send _two_ breakpoints to the server so that the breakpoint fires regardless of whether the `.bzl` file was loaded using a repository-qualified path or not. 😕

**Comment by ittaiz** [comment]
I’m fairly confident you’re working around a bug @dkelmer is working on
w.r.t label equality.
This isn’t WAI and the symlink of the “current repo” bzl should not point
to external.
If you want I can try and find the bazel bug.

**Comment by allevato** [comment]
This appears to be the Bazel issue: https://github.com/bazelbuild/bazel/issues/6848
