### ISSUE TITLE
checked in .vscode directory causing 2 issues

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/vscode-bazel#255]
When I go to edit `scripts/build.sh`, prettifier tells me it's configured to be the default formatter, but that it can't support shell languages. When I change the shell formatter to one that works, I see that the local `.vscode/settings.json` has been updated. That doesn't seem desirable for other folks, tho.

I've also noticed that the `.vscode/tasks.json` file is being auto-upgraded by my vscode from `0.10` to `2.0.0` and makes significant changes to the file. I was going to post a PR that includes those task.json changes, but that got me thinking.

Given how much change is user-dependent, would it make sense for me to send a PR that removes `.vscode` from the repo instead?

**Comment by jmhodges** [comment]
Made a quick not for submission PR to demo the problem: https://github.com/bazelbuild/vscode-bazel/pull/257

**Comment by cameron-martin** [comment]
Looks like the tasks.json issue is fixed here: https://github.com/bazelbuild/vscode-bazel/pull/274

The `editor.defaultFormatter` should be scoped to just `[typescript]`. I'll put up a PR for this later.

**Comment by jmhodges** [comment]
Thank you!
