### ISSUE TITLE
Feature request: syntax support for bazelrc files

### ISSUE THREAD

**Issue by adam-azarchs** [bazelbuild/vscode-bazel#259]
Currently vscode detects bazelrc files as being shell scripts, which leads to sub-optimal syntax highlighting and also spurious warnings if you have any extensionsenabled  (e.g. [`shellcheck`](https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck)) which operate on shell scripts.

The grammar for bazelrc files seems straightforward, so it seems like it would be fairly trivial to add one in to pick up `.bazelrc` or `bazelrc` files.  I'm happy to implement this and make a PR if the maintainers are open to it.

**Comment by jbajic** [comment]
I support this request as well

**Comment by adam-azarchs** [comment]
No I don't have a draft; it's not to make a grammar for it but I wasn't going to bother without confirmation that it would be likely to get accepted.

Of course I'm talking about a "dumb" grammar file.  A smarter one would have a list of known flags and which commands they apply to, which would be neat, but more effort.

**Comment by cameron-martin** [comment]
Happy to accept a PR. This seems like a good feature.

**Comment by vogelsgesang** [comment]
I just open-source https://github.com/salesforce-misc/bazelrc-lsp, in case anyone is interested
