### ISSUE TITLE
Extension causes OOM of Remote Extension Host in large codebase

### ISSUE THREAD

**Issue by chunyang** [bazelbuild/vscode-bazel#296]
Type: <b>Bug</b>

When the Bazel extension is enabled, the extension host memory usage creeps up until eventually an OOM occurs. I narrowed down the extensions using Extension Bisect to the Bazel extension. I can reproduce the OOM in all the versions of the extension that I tried (0.7.0, 0.6.0, 0.5.0).

Extension version: 0.7.0
VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No
Connection to 'SSH: shell' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--file-uri=vscode-remote://ssh-remote+shell/home/chuck.yang/workspaces/p3/p3.code-workspace --skip-welcome --skip-release-notes --skip-add-to-recently-opened --disable-workspace-trust|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: shell' could not be established  Canceled
</details>

**Comment by desponda** [comment]
+1 im also running into this issue with large repositories

**Comment by marchmallow** [comment]
> +1 im also running into this issue with large repositories

Yeah basically this makes the extension unusable for us at Datadog atm.
