### ISSUE TITLE
Custom path to Bazel binary?

### ISSUE THREAD

**Issue by ted-xie** [bazelbuild/vscode-bazel#298]
Hi there,

I work mostly with Bazel@HEAD, which requires either building bazel myself from source, or using something like `USE_BAZEL_VERSION=last_green bazelisk build [something]`. Is it possible to either provide a path to a custom bazel binary in the vscode-bazel plugin, or invoke bazelisk instead? Happy to collaborate/contribute on this feature if it doesn't exist already, and if it's not a significant maintenance burden.

**Comment by ted-xie** [comment]
My temporary workaround for this is to set `USE_BAZEL_VERSION=last_green` in my ~/.bashrc, and  `sudo mv /usr/bin/bazelisk /usr/bin/bazel`. Quite unsavory but it works, and now I'm able to properly use the plugin.

**Comment by beasleyr-vmw** [comment]
> Is it possible to either provide a path to a custom bazel binary in the vscode-bazel plugin, or invoke bazelisk instead?

Apologies if I'm missing something (I'm new to VSCode), but afaict there's already a configuration setting for this: `bazel.executable`. Am I missing anything? (Settings > Workspace > Bazel > Bazel: Executable.)

**Comment by ted-xie** [comment]
Ah, cool! I did not find that back in March. Thanks for the pointer.
