### ISSUE TITLE
Recognize WORKSPACE.bzlmod as Bazel build file an put a proper icon on it

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/vscode-bazel#301]
Recognize `WORKSPACE.bzlmod` as Bazel build file an put a proper icon on it.

Currently VSCode shows `MODULE.bazel`, `WORKSPACE.bazel` and some other Bazel related files with small Bazel icons in the Explorer - but this does not work for `WORKSPACE.bzlmod`:

![image](https://github.com/bazelbuild/vscode-bazel/assets/3775001/3a5af620-cc6e-492d-8bd6-d47e33823e4b)

Would be nice if `WORKSPACE.bzlmod` would also be shown with a small Bazel icon in the Explorer

**Comment by hypdeb** [comment]
It seems this could be an issue for VC Code itself rather than for the extension. I have the icons even without the extension installed.

**Comment by hofbi** [comment]
Should be fixed by https://github.com/bazelbuild/vscode-bazel/pull/313
