### ISSUE TITLE
Failed to find a Bazel workspace

### ISSUE THREAD

**Issue by hofbi** [bazelbuild/vscode-bazel#314]
We switched to bazel mod and already got rid of our `WORKSPACE` file. We only have a `MODULE.bazel` file. Opening my workspace, I get a `Failed to find a Bazel workspace` error from the plugin. It looks like the plugin does not support bazel mod yet and is expecting a `WORKSPACE` file.

To reproduce this issue, just create a new project with a `MODULE.bazel`, but without a `WORKSPACE` file.

**Comment by hypdeb** [comment]
I don't think you can get rid of the `WORKSPACE` file by using `Bzlmod`. They serve different purposes. In the [documentation](https://docs.bazel.build/versions/5.1.0/bzlmod.html#modulebazel), they say the `MODULE.bazel` file should reside next to to the `WORKSPACE` file:

> The MODULE.bazel file should be located at the root of the workspace directory (next to the WORKSPACE file). Unlike with the WORKSPACE file, you don’t need to specify your transitive dependencies; instead, you should only specify direct dependencies, and the MODULE.bazel files of your dependencies will be processed to discover transitive dependencies automatically.

It seems that in 7.0 [they plan on replacing the workspace file](https://docs.bazel.build/versions/5.1.0/bzlmod.html#modulebazel) with a `REPO.bazel` file. I'm not sure why though.

**Comment by hofbi** [comment]
You are referring to the documentation bazel 5.1.0. In the [bazel mod migration guide](https://bazel.build/external/migration#define-root), I can see

> The WORKSPACE file marks the source root of a Bazel project, this responsibility is replaced by MODULE.bazel in Bazel version 6.3 and later. With Bazel version prior to 6.3, there should still be a WORKSPACE or WORKSPACE.bazel file at your workspace root

**Comment by hypdeb** [comment]
Yeah, you're right. But I'm confused now as to what the new `REPO.bazel` file is supposed to be do.

**Comment by hypdeb** [comment]
In any case, I can fix that I think, I'll just wait until my previous PR is merged.

**Comment by hofbi** [comment]
https://bazel.build/external/overview seems like a good reference, but I am also not sure about the `REPO.bazel` file. For workspace vs bazelmod, I think 

> As of Bazel 6.0, there are two ways to manage external dependencies with Bazel: the traditional, repository-focused [WORKSPACE system](https://bazel.build/external/overview#workspace-system), and the newer module-focused [MODULE.bazel system](https://bazel.build/external/overview#bzlmod) (codenamed Bzlmod, and enabled with the flag --enable_bzlmod). The two systems can be used together, but Bzlmod is replacing the WORKSPACE system in future Bazel releases, check the [Bzlmod migration guide](https://bazel.build/external/migration) on how to migrate.

is a good summary. 

At BazelCon I learned that the WORKSPACE file support should be removed with Bazel 9.

**Comment by hypdeb** [comment]
It seems like #323 should do it.

**Comment by cameron-martin** [comment]
@hofbi Can you confirm that PR fixes your issue?

**Comment by hofbi** [comment]
Yes looks good.
