### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by cameron-martin** [bazelbuild/vscode-bazel#318]
CI on PRs is failing on an error when running apt-get update:

```
W: GPG error: http://packages.cloud.google.com/apt cloud-sdk InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0BA5CE6DC6315A3
E: The repository 'http://packages.cloud.google.com/apt cloud-sdk InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

See for example [this build](https://buildkite.com/bazel/vscode-bazel-vs-bazel/builds/2045#018c83ee-bf3c-4202-9b4b-26311754c348).

Not exactly sure what is causing this.

**Comment by daivinhtran** [comment]
This appears to be flaky across PRs but consistent within a PR? 

I'm having the same failure in https://github.com/bazelbuild/vscode-bazel/pull/322 but not in https://github.com/bazelbuild/vscode-bazel/pull/320.

**Comment by daivinhtran** [comment]
Ah nevermind. I just had [a linting error](https://github.com/bazelbuild/vscode-bazel/pull/322/commits/72e22a99b0129cd3373ee4e319fa1617972238ef). It's green now. You might want to try pushing an empty commit to retrigger CI.

**Comment by cameron-martin** [comment]
Seems like it was just a transient issue
