### ISSUE TITLE
Why does commandArgs not apply to Run targets?

### ISSUE THREAD

**Issue by makestuff** [bazelbuild/vscode-bazel#394]
Is there a reason “run” is not included in the list of things to add commandArgs to? I have some options which should apply equally to build, test and run targets.

https://github.com/bazelbuild/vscode-bazel/blob/e5c95e4567a80c82ada48031c9fde5561fc7c957/src/bazel/tasks.ts#L229-L230

**Comment by vogelsgesang** [comment]
Good question. I also already wondered the same...
