### ISSUE TITLE
Syntax highlighting of `and`/`or`/`not`/`in` in Starlark

### ISSUE THREAD

**Issue by nicolasstucki** [bazelbuild/vscode-bazel#396]
The following rule matches those keywords but do not result in any highlighting.
 https://github.com/bazelbuild/vscode-bazel/blob/e5c95e4567a80c82ada48031c9fde5561fc7c957/syntaxes/starlark.tmLanguage.json#L397

<img width="210" alt="Screenshot 2024-05-17 at 11 36 48" src="https://github.com/bazelbuild/vscode-bazel/assets/3648029/1e230922-0313-498e-9441-f7239467cac5">

These are currently tagged as 
https://github.com/bazelbuild/vscode-bazel/blob/e5c95e4567a80c82ada48031c9fde5561fc7c957/syntaxes/starlark.tmLanguage.json#L400

**Comment by vogelsgesang** [comment]
According to the documentation at https://macromates.com/manual/en/language_grammars (which is referenced by the [VSCode docs](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide)), `keyword.operator.*` seems to be the right way to go. I wonder where the `keyword.language.*` is defined...

**Comment by vogelsgesang** [comment]
Also VSCode has [a lot of mentions](https://github.com/search?q=repo%3Amicrosoft%2Fvscode+keyword.operator.logical&type=code) of `keyword.operator.logical` but [not a single mention](https://github.com/search?q=repo%3Amicrosoft%2Fvscode+keyword.language&type=code) of `keyword.language`

**Comment by nicolasstucki** [comment]
I see. My patch probably ended up falling back on [`keyword`](https://github.com/microsoft/vscode/blob/5d6671dacb9d6a582b9354ea317211a8e2b2f918/extensions/theme-defaults/themes/dark_vs.json#L323-L326) and therefore used the same highlighting as in [`keyword.operator.logical.python`](https://github.com/microsoft/vscode/blob/5d6671dacb9d6a582b9354ea317211a8e2b2f918/extensions/theme-defaults/themes/dark_vs.json#L350). The issue here seems to be that the highlighting of those operators as keywords is special-cased for Python with `keyword.operator.logical.python` and hence we do not get the same effect with `keyword.operator.logical.starlark`.

**Comment by vogelsgesang** [comment]
I wonder if we should use `keyword.operator.logical.python.starlark`. That way we would inherit the styles from Python by default, but theme authors would still have the option to provide Starlark specific styles, if they wish to do so

**Comment by nicolasstucki** [comment]
`keyword.operator.logical.python.starlark` is an interesting approach. If we take this approach would we also change all others `.starlark` to `.python.starlark` to inherit all existing highlighings? This would imply changing around 100 names.

**Comment by vogelsgesang** [comment]
Personally, I would just rename all of them, for consistency. But others might have different opinions...
Could you create a PR? And then let's see if anybody dislikes the renaming during the review

**Comment by nicolasstucki** [comment]
Yes @vogelsgesang, I can create a PR with this change.
