### ISSUE TITLE
Add a configuration option to filter the Bazel target tree view

### ISSUE THREAD

**Issue by allevato** [bazelbuild/vscode-bazel#51]
Many times, BUILD files contain macros that generate targets that are purely implementation details that are meant to be hidden from the user (for example, `ios_application` currently produces a handful of extra targets to work around current limitations in Bazel's APIs). These targets are just noise in the tree, so we should have a config setting that lets users specify a list of rule classes (or patterns) that shouldn't be shown.

**Comment by jfirebaugh** [comment]
Done inhttps://github.com/bazelbuild/vscode-bazel/pull/286.
