### ISSUE TITLE
gdb seems to inject the build executable, not the actual testing executable

### ISSUE THREAD

**Issue by ymd-ponyai** [bazelbuild/vscode-bazel#57]
Steps to reproduce:
Explorer -> Bazel build targets -> right click target -> build target with debugging

vs code version:
Version: 1.31.0
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-06T08:51:24.856Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.13.0-31-generic

vscode-bazel version: Version 0.1.0 (January 23, 2019)

Debug console output
```
INFO: Debugger connection successfully established.
Loading: 
Loading: 0 packages loaded
DEBUG: /home/ymd/ponyai/.sub-repos/common/third_party/bazel.bzl:5:5: Bazel version: 0.18.1
INFO: Analysed target //my:target (0 packages loaded).
INFO: Found 1 target...
[0 / 2] [-----] BazelWorkspaceStatusAction stable-status.txt
[0 / 4] [-----] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 1 running)
[1 / 4] Compiling my/source/file.cc; 4s linux-sandbox
[2 / 4] Linking my/target; 11s linux-sandbox
Target //my:target up-to-date:
  my/executable
INFO: Elapsed time: 81.721s, Critical Path: 78.27s
INFO: Build completed successfully, 3 total actions
INFO: Debug server listener thread closed; shutting down debug server and resuming all threads
```

`my/executable` is not executed.

**Comment by ymd-ponyai** [comment]
also, the built executable is not built with `-c dbg`

**Comment by allevato** [comment]
The "Build with Debugging" feature is intended to debug the _build rules themselves_, not the target being built. In other words, it lets you set breakpoints and step through the rule definitions in your `.bzl` files. This feature is intended for users who are authoring custom build rules.

To debug executables built with Bazel, you'll need to use the appropriate debug configurations and extensions for that language. You can add a Bazel build task though as a pre-launch task for that debug configuration though to make sure that your executable is built before trying to launch it.

**Comment by ymd-ponyai** [comment]
Thank you for the quick response!

Tony Allevato <notifications@github.com>于2019年2月8日 周五08:06写道：
