### ISSUE TITLE
List of targets never loads

### ISSUE THREAD

**Issue by jfroy** [bazelbuild/vscode-bazel#58]
I am working in a fairly complex workspace, with many targets, external workspaces, etc. The list of targets never loads, and the extension host process is pegged at 100% CPU.

Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.16-1rodete1-amd64

Using version 0.1.0.

**Comment by allevato** [comment]
About how large is the workspace (how deep is its package structure, how many external dependencies, etc.)?

If you run the **Developer: Toggle Developer Tools** command, do you see any logging that looks relevant in the console?

When the tree first loads, it runs `bazel query //... --output=package` in your workspace directory to get the full list of packages. If you run that from the command line, does it take a long time to finish? If not, how many lines is the output?

**Comment by allevato** [comment]
Can you check this again with the latest release (0.2.0) of the extension on the marketplace? We fixed a couple issues that may have been causing this.

**Comment by jfroy** [comment]
We're seeing this error now. It may be a problem in our WORKSPACE:

```
Command failed: bazel query ...:* --output=package
Loading: 0 packages loaded
Loading: 543 packages loaded
    currently loading: vendor/google.golang.org/api/pagespeedonline/v4
Loading: 892 packages loaded
    currently loading: third_party/libvpx
ERROR: error loading package 'bazel-master/external/bazel_tools/src/main/protobuf': Label '//tools/build_rules:genproto.bzl' crosses boundary of package 'tools' (perhaps you meant to put the colon here: '//tools:build_rules/genproto.bzl'?)
Loading: 1123 packages loaded
    currently loading: bazel-master/external/bazel_tools/src/tools/launcher/util ... (2 packages)
Loading: 1123 packages loaded
    currently loading: bazel-master/external/bazel_tools/src/tools/launcher/util ... (2 packages)
```

**Comment by jfroy** [comment]
```Build label: 0.25.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 10 20:47:48 2019 (1557521268)
Build timestamp: 1557521268
Build timestamp as int: 1557521268```

**Comment by allevato** [comment]
That does look like a problem specifically in one of the BUILD files in your workspace, rather than a problem with the extension, since Bazel is launching properly. I'm going to close out this issue, but feel free to reopen it if you investigate and believe the issue is related.
