### ISSUE TITLE
Implement debug server

### ISSUE THREAD

**Issue by allevato** [bazelbuild/vscode-bazel#6]
Once the basic UI to select and build targets goes in (#5), we'll have enough of a front-end in place that I can start moving my debugger prototype over.

**Comment by ittaiz** [comment]
@laurentlb you mentioned one can already debug starlark code in vscode. Is it in the open yet or will take some more time? Just had the need for debugging rules_scala and was hoping to skip print debugging :)

**Comment by allevato** [comment]
It's still a work in progress—I've checked in part of the implementation to add the UI to build targets with the debugger enabled, but it doesn't monitor thread state or stop on breakpoints yet.

Keep an eye on the repo—I'm hoping to have a usable debugging experience up here soon.
