### ISSUE TITLE
vscode-bazel hangs: "took a very long time to complete its last operation"

### ISSUE THREAD

**Issue by ricebucket** [bazelbuild/vscode-bazel#60]
vscode is reporting in the status that:
`The extension 'vscode-bazel' took a very long time to complete its last operation and it has prevented other extensions from running.`
Looking at the running extensions and it shows 20ms activation and a Profile of over 5000ms.

In addition it seems that all of the plugin features are not working. For example, I'm not seeing any build targets. It is also prevent my other plugins from working.

Any way I can go about debugging this? Right now I have to keep the plugin disabled.

**Comment by allevato** [comment]
How large is your Bazel workspace? I wonder if you're hitting a problem similar to #58.

If I had to wager a guess, I'd suspect that the Bazel Build Targets tree view is causing issues when the workspace loads, because it queries the list of all packages (but not targets) in the workspace to show the top-level nodes. But that should all be happening in the background, not blocking the UI.

Can you try the suggestions I mentioned in https://github.com/bazelbuild/vscode-bazel/issues/58#issuecomment-465181485 to see if there's any info we can gather to narrow the problem down?

**Comment by ricebucket** [comment]
`bazel query //... --output=package` returns 39 lines and is very fast. I don't consider this workspace to be very large. A lot of targets have only 1 or two files. 

However, there are some targets that currently do not build (are broken). Could this be the cause?

Developer: Toggle Developer Tools does not reveal much besides the warning about the extension taking too long (and some data fields). 

The extension worked for me a few days ago on the same workspace. It may be due to some other config changes I made but I don't know how to trace this.

**Comment by allevato** [comment]
As long as the package query returns successfully, the broken targets shouldn't be an issue. The only non-user-initiated thing the extension does right now is populate the root of that tree; building anything else would be something you'd have to invoke a command to run. I'd be interested to know whether fixing those targets changes the behavior you're observing, though.

Just to be sure, you're using the latest release (0.1.0) and not building the extension from the latest source, correct?

**Comment by ricebucket** [comment]
Yes I'm using the latest release from the extensions marketplace. Is there anything I can do to trace at which step the extension is stuck?

And one more note: even when the extension was working a few days ago, I never saw anything on the build targets pane. (But I was able to see the code lens links in BUILD files to build the targets, for example. And clicking on them built the targets successfully.)

**Comment by allevato** [comment]
You could try checking out the latest code and running the extension host in the debugger, but I would think that if you were going to get something useful out of that, then you'd also be seeing something useful in the Developer Tools console.

How heavy are your external repository dependencies? I wonder if there's a way that you could strip down and redact your workspace to the bare minimum that exhibits this problem, which would at least let you send it over so we could debug it better.

**Comment by ricebucket** [comment]
I do have a lot of external dependencies, git_repository, http_archive etc. Does the extension re-download all of these dependencies in a separate space or something?

**Comment by allevato** [comment]
It shouldn't—it'll use the same output directories as if you were building from the command line. But I'm trying to consider all possibilities since I'm not sure what's going on here 🤔

**Comment by ricebucket** [comment]
I found the following in the CPU profile log:
(showing only the subset with the most "hitCount")
```
        {
            "id": 26,
            "callFrame": {
                "functionName": "fromWorkspaceFolder",
                "scriptId": "429",
                "url": "pii_removed/bazel_workspace_info.js",
                "lineNumber": 65,
                "columnNumber": 30
            },
            "hitCount": 356,
            "children": [
                27,
                36,
                49
            ],
            "positionTicks": [
                {
                    "line": 66,
                    "ticks": 356
                }
            ]
        },
        {
            "id": 27,
            "callFrame": {
                "functionName": "exports.wrapFsWithAsar.fs.accessSync",
                "scriptId": "54",
                "url": "ELECTRON_ASAR.js",
                "lineNumber": 476,
                "columnNumber": 29
            },
            "hitCount": 892,
            "children": [
                28,
                32,
                42,
                55,
                56,
                61
            ],
            "positionTicks": [
                {
                    "line": 477,
                    "ticks": 274
                },
                {
                    "line": 479,
                    "ticks": 618
                }
            ]
        },
        {
            "id": 28,
            "callFrame": {
                "functionName": "fs.accessSync",
                "scriptId": "30",
                "url": "fs.js",
                "lineNumber": 219,
                "columnNumber": 24
            },
            "hitCount": 1185,
            "children": [
                29,
                33,
                34,
                39,
                47
            ],
            "positionTicks": [
                {
                    "line": 224,
                    "ticks": 20
                },
                {
                    "line": 220,
                    "ticks": 221
                },
                {
                    "line": 229,
                    "ticks": 863
                },
                {
                    "line": 230,
                    "ticks": 81
                }
            ]
        },
        {
            "id": 29,
            "callFrame": {
                "functionName": "handleErrorFromBinding",
                "scriptId": "30",
                "url": "fs.js",
                "lineNumber": 138,
                "columnNumber": 31
            },
            "hitCount": 8222,
            "children": [
                30,
                44,
                57,
                58,
                59
            ],
            "positionTicks": [
                {
                    "line": 139,
                    "ticks": 8222
                }
            ]
        },
        {
            "id": 30,
            "callFrame": {
                "functionName": "uvException",
                "scriptId": "20",
                "url": "internal/errors.js",
                "lineNumber": 244,
                "columnNumber": 20
            },
            "hitCount": 15913,
            "children": [
                31,
                40,
                46,
                48,
                51,
                52,
                54,
                60
            ],
            "positionTicks": [
                {
                    "line": 246,
                    "ticks": 184
                },
                {
                    "line": 247,
                    "ticks": 2
                },
                {
                    "line": 280,
                    "ticks": 7716
                },
                {
                    "line": 263,
                    "ticks": 7964
                },
                {
                    "line": 265,
                    "ticks": 2
                },
                {
                    "line": 252,
                    "ticks": 10
                },
                {
                    "line": 253,
                    "ticks": 1
                },
                {
                    "line": 269,
                    "ticks": 34
                }
            ]
        },
```
Does this help?

**Comment by allevato** [comment]
Nothing in that log _immediately_ jumps out to me, but the fact that there's so many instances of an error handling function firing makes me wonder if something in the Bazel invocation is failing and it's getting stuck in some kind of tight loop. I'm not sure how, though.

You said you had some build targets that fail to build; I don't think those would matter since we just query packages and you said that was successful, but does fixing those targets (if you can) make the problem go away?

Would you be able to create an empty workspace and start slowly adding some of your external dependencies and some dummy targets to it, just to see if the problem starts that way?

**Comment by allevato** [comment]
Can you check this again with the latest release (0.2.0) of the extension on the marketplace? We fixed a couple issues that may have been causing this.

**Comment by ricebucket** [comment]
I tested the new version today and everything fixed itself. Thanks!
