### ISSUE TITLE
Error when "Build Target" in zsh : command not found: build

### ISSUE THREAD

**Issue by laphets** [bazelbuild/vscode-bazel#63]
Test in zsh. Which is shown in the attachment.
![image](https://user-images.githubusercontent.com/12796233/53463588-4340f200-3a82-11e9-902f-40867c63bbb3.png)

**Comment by allevato** [comment]
Can you provide any more information? Is `bazel` located somewhere on your system path? Did you change your user/workspace configuration to point it to a different location?

**Comment by rynz** [comment]
I have the same issue, `bazel` is in my `$PATH` and I can access it with terminal. However whenever I try to build a target, whether that be in a `BUILD` file or `BAZEL BUILD TARGETS` I get the error:
```
/bin/bash: build: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```
Why is it trying to call a command `build` rather than `bazel`?

**Comment by smukherj1** [comment]
@laphets and @rynz, can you check your settings.json? Do you have a "bazel" field set to something? The logic that determines the bazel executable to use is here https://github.com/bazelbuild/vscode-bazel/blob/995dfbc0ec956d4ccd9a46ffac1d8318c14050e6/src/bazel/bazel_command.ts#L90

It will use a "bazel" configuration if specified in the settings.json or fall back to "bazel". One possibility is if the "bazel" field is set to one or more spaces, this issue could arise.

**Comment by rynz** [comment]
@smukherj1 `vscode-bazel` is installed fresh without any configuration.

`settings.json`:
```json
{
    "window.titleBarStyle": "custom",
    "workbench.colorTheme": "Monokai",
    "editor.tabSize": 2,
    "editor.rulers": [
        80
    ],
    "window.zoomLevel": 0,
    "workbench.sideBar.location": "left",
    "editor.fontSize": 13,
    "editor.minimap.enabled": true,
    "C_Cpp.clang_format_fallbackStyle": "Google"
}
```
`defaultSettings.json`:
```json
{
  "bazel.buildifierExecutable": "",
  "bazel.buildifierFixOnFormat": false,
  "bazel.executable": ""
}
```

https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration looks to have getter methods now? Perhaps `getDefaultBazelExecutablePath` needs to call `get` with a `defaultValue` rather than accessing it as an object?

**Comment by rynz** [comment]
It doesn't appear to be related to `getDefaultBazelExecutablePath` as it calls `query` on startup without any issues. Only when attempting to build within the `BUILD` file or `Bazel Build Targets` tree.
