### ISSUE TITLE
"Unable to open" on Windows

### ISSUE THREAD

**Issue by jblanchet** [bazelbuild/vscode-bazel#65]
Using the plugin on Windows, any item I click on in the 'BAZEL BUILD TARGETS' list shows an error dialog:

![image](https://user-images.githubusercontent.com/7320670/53597125-32fa4700-3b56-11e9-80f4-c89d7ff1c47a.png)

In this case, I'm working on my D drive.

**Comment by allevato** [comment]
Admittedly Windows is not a platform I've tested on (nor do I really have the setup to test on).

If anyone is willing and able to help out with that platform, it would be appreciated!

**Comment by jblanchet** [comment]
I may have some time in a week or so to take a crack at getting this to work on windows. Any specific thoughts @allevato?

**Comment by allevato** [comment]
I haven't used Windows in about 15 years, so I wouldn't know where to begin 😅   Check the console log in the Developer Tools window to see if there's anything useful there. It's possible that I'm constructing a path or a file URL in a way that's incompatible with the Windows drive letter separator, but I would hope using the standard Node and VS Code APIs would ensure those are correct.

**Comment by jblanchet** [comment]
Sounds good, hopefully I'll get to it in about 10 days. Thanks.
