### ISSUE TITLE
[Windows] "Buildifier was not found;" each time

### ISSUE THREAD

**Issue by r44083** [bazelbuild/vscode-bazel#70]
Hi, I have noticed that vscode-bazel pop ups "Buildifier was not found;" error on each startup despite of buildifier existence.

I check it, buildifier is present within PATH and I can call it from internal console by typing ```buildifier```

![image](https://user-images.githubusercontent.com/13915612/54447488-3abf0b80-4752-11e9-985d-f3fd57b2e0ca.png)

Another strange point is that ```buildifier``` file for windows has no extension. So, it couldn't be executed in console. I downloaded buildifier from https://github.com/bazelbuild/buildtools/releases

**Could you please help me to solve this?**

**Comment by thomasvl** [comment]
If you downloaded the `buildifier` from https://github.com/bazelbuild/buildtools/releases, that's a linux binary.  It doesn't look like they provide Windows binaries.  I opened https://github.com/bazelbuild/buildtools/issues/582 requesting they provide Windows binaries.

**Comment by Globegitter** [comment]
I am having the same issue on Mac OSX and I download the mac version of the binary. I can call:

```
buildifier -version
buildifier version: 0.25.0
buildifier scm revision: b78a2269cf8338893446e722bddfc75ed2374d1
```

I also tried providing the absolute PATH to buildifier but I still get the same error every time.

**Comment by thomasvl** [comment]
Windows binaries of buildifier are now provided by the [buildtools project](https://github.com/bazelbuild/buildtools/releases)

@Globegitter given this issue was specific to Windows (and not having a Windows binary installed), it might not make sense to use this for other platforms.

**Comment by allevato** [comment]
> Windows binaries of buildifier are now provided by the [buildtools project](https://github.com/bazelbuild/buildtools/releases)

Closing since these are now available.

> @Globegitter given this issue was specific to Windows (and not having a Windows binary installed), it might not make sense to use this for other platforms.

Yes, please file a separate issue if this message pops up on other platforms.
