### ISSUE TITLE
Bazel Build Targets doesn't list root targets

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/vscode-bazel#71]
Some package, since they are likely to be used by other larger builds, have very basic BUILD files, so they only need targets at the root of their workspace.  The _Bazel Build Targets_ panel doesn't seem to be able to support/show this.

`git clone --recursive https://github.com/protocolbuffers/protobuf.git` and then open that folder, and you'll see you can't act on any of the targets in the side bar.  Code Lens when looking at the BUILD file does work through.

**Comment by allevato** [comment]
Duplicate of #46.

**Comment by thomasvl** [comment]
Sorry, I searched but failed.
