### ISSUE TITLE
Build all targets inside a package

### ISSUE THREAD

**Issue by A-Sam** [bazelbuild/vscode-bazel#72]
ATM, all targets are being loaded in the view (Bazel build targets). Every time i want to run all the targets inside a package i have to write the 1 liner for loop in bash to build all targets read from $(bazel query //...). It would be good option to add to this view.

**Comment by thomasvl** [comment]
fyi - `bazel build //...`, no need for the query; you can also do `bazel build //package:all` to build everything in the package, but not do it recursively.

**Comment by A-Sam** [comment]
Yeah. I use the query though to see the targets prior building and saving them to a file(smth like a dry-run). But I think it would be nice to add a feature on Bazel Build Targets to run all targets under a specific package in the extension.

**Comment by thomasvl** [comment]
Now that we have the right click on the packages in the tree view, we could also change the treeview code to always show the opened directory node even when only one directory is open in VS Code, that catch is that directory might not have a BUILD file (it could be some random place within the overall bazel workspace).  So building `:all` there would error, but `...` would work, so the code would need to know to only enable some vs. all of the commands.

**Comment by A-Sam** [comment]
Bazel build //target/... will build all targets in the package which is what i originally meant and use.. thumbs up! Will this be released any time soon?

**Comment by thomasvl** [comment]
The 0.2.0 release in May should have had it.

**Comment by allevato** [comment]
Closing because this was released in 0.2.0.

**Comment by oliverdain** [comment]
It does not seem to be possible to build `//...`. If I select `Bazel build package recursively` I have to select a package and `//` is not an option. I have tons of packages so it'd be really nice to be able to just build all of them.

**Comment by thomasvl** [comment]
Please open a new issue specific to the whole WORKSPACE cases.
