### ISSUE TITLE
Interferes with ibazel 

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/vscode-bazel#75]
Using the vscode plugin, every time a file is saved it seems to do same `bazel query` calls to the local bazel server.

If you're also running a watch mode at the same time, it takes a long time to get a result in the ibazel session because the server is locked:

```
Build graph changed: "/usr/local/google/home/alexeagle/Projects/angular-bazel-example/src/lib/shorten/BUILD.bazel". Requerying...
Querying for files to watch...
Starting local Bazel server and connecting to it...
Loading: 0 packages loaded
Loading: 9 packages loaded
    currently loading: @build_bazel_rules_nodejs//internal/web_package ... (12 packages)
Loading: 375 packages loaded

Loading: 375 packages loaded
Another command holds the client lock: 
pid=147569
owner=client
cwd=/usr/local/google/home/alexeagle/Projects/angular-bazel-example

Waiting for it to complete...
Another command holds the client lock: 
pid=147575
owner=client
cwd=/usr/local/google/home/alexeagle/Projects/angular-bazel-example

Waiting for it to complete...
Starting local Bazel server and connecting to it...
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 375 packages loaded

Loading: 375 packages loaded
Runing //src:devserver
Notifying of changes
Loading: 
Loading: 0 packages loaded
Analyzing: target //src:devserver (0 packages loaded, 0 targets configured)
Analyzing: target //src:devserver (5 packages loaded, 26419 targets configured)
INFO: Analysed target //src:devserver (5 packages loaded, 26424 targets configured).
INFO: Found 1 target...
[0 / 3] [-----] BazelWorkspaceStatusAction stable-status.txt
[27 / 40] checking cached actions
[43 / 48] Compiling TypeScript (devmode) //src/lib/shorten:shorten; 0s worker
[45 / 48] Compiling Angular templates (ngc) //src/app/hello-world:hello-world; 0s worker
[45 / 48] Compiling Angular templates (ngc) //src/app/hello-world:hello-world; 1s worker
[46 / 48] Compiling Angular templates (ngc) //src/app:app; 0s worker
Target //src:devserver up-to-date:
  dist/bin/src/devserver_launcher.sh
  dist/bin/src/devserver
INFO: Elapsed time: 10.939s, Critical Path: 6.00s
INFO: 4 processes: 4 worker.
INFO: Build completed successfully, 9 total actions
INFO: Build completed successfully, 9 total actions
SUCCESS
Error writing success to stdin: write |1: broken pipe
Triggering live reload
requesting reload: reload
```

somehow these two need to play nicely together

**Comment by allevato** [comment]
When you say "every time a file is saved", do you mean *any* file in the workspace, or just BUILD files? We have logic to do a query when a BUILD file is saved so that the Bazel Build Targets tree view is automatically updated if you add/remove targets, but it shouldn't be triggered for other files.

I don't know much about `ibazel`, so it's not immediately clear to me what the resolution is here.

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/bazel-watcher is the "watch mode" for Bazel and it's somewhere in between community contrib and Bazel first-party supported.

Yes, I believe the change I was making there was to a BUILD file.

**Comment by mariusgrigoriu** [comment]
This isn't just a problem with ibazel. The lock prevents regular bazel commands from running in the terminal.

**Comment by achew22** [comment]
Could we put together a gist that demonstrated the issue at hand? I think that would provide some much needed clarity

**Comment by mariusgrigoriu** [comment]
I don't have a repro available, but I observed this during a live share session.

The Bazel docs recommend setting `--output_base` if you are scripting queries to avoid contending for the lock. https://docs.bazel.build/versions/master/guide.html#choosing-the-output-base

**Comment by alexeagle** [comment]
Another major flaw is when the user runs bazel with some startup flags that differ from vscode extension. Then they see the Bazel server restarting for every command they run.

**Comment by thomasvl** [comment]
> Another major flaw is when the user runs bazel with some startup flags that differ from vscode extension. Then they see the Bazel server restarting for every command they run.

Trunk already has prefs to allow adding other options to the invokes the extension does.

**Comment by allevato** [comment]
With #160 merged, I think we can close this out. The next version of the extension will by default use a separate `--output_base` for queries, which should resolve issues with `ibazel` (and other uses of query from the extension during long-running build tasks). Thanks to @mariusgrigoriu for pointing us at the tip about that in the docs!

**Comment by muratbeser** [comment]
![image](https://user-images.githubusercontent.com/2212213/77601685-77ecda80-6f1c-11ea-91c6-b6bc9bdc4fac.png)
I'm still having this issue. I'm runing iBazel via npx.

**Comment by thomasvl** [comment]
The 0.3.0 release was in September, the fix listed here was landed in Dec, so unless you built your own copy of the extension you likely don't have the fix yet.

**Comment by muratbeser** [comment]
@thomasvl no it is not. with `npx` or with `yarn ibazel` commands I do have the same issue `yarn ibazel` has perfomance impact. it might be my setup I'm not sure. currently I run this too often.
