### ISSUE TITLE
Filter targets based on search pattern in the tree view

### ISSUE THREAD

**Issue by A-Sam** [bazelbuild/vscode-bazel#86]
#50 and #84 sort the targets in the tree view. It would be nice to be able to search the tree for a specific pattern.

**Comment by thomasvl** [comment]
I'm not sure if this is a dup of #51 or if you are just looking for a way to filter while viewing the tree temporarily.  If it just a way to filter temporarily, this is already built into VSCode

https://github.com/microsoft/vscode-docs/blob/master/release-notes/v1_37.md#new-tree-widget-adopted-in-tree-view

> **New tree widget adopted in tree view**
>
> Extensions that contribute tree views will now get the [new tree widget](https://code.visualstudio.com/updates/v1_31#_new-tree-widget) experience. The tree widget provides better performance as well as improved keyboard navigation, filtering, custom indenting, horizontal scrolling, and more. If your favorite extensions have custom tree views, you should see the same UX improvements that were added earlier to the built-in VS Code explorers.

So the view provided by the extension how gets the support (follow the link to older note for more details on how it works).

**Comment by A-Sam** [comment]
The issue is that the filtered result is based on greedy search as shown:
![image](https://user-images.githubusercontent.com/11005214/68993117-ad016600-0874-11ea-9aa9-e4a00b795c22.png)

while i think it would be nice to have a non-greedy filter option. Because with huge list of targets, greedy regex shows a lot non-relevant targets that eat all space. Here, I would expect to see no targets in this list for 'mib'.


I think it can be an issue of VSC not the extension.

**Comment by A-Sam** [comment]
I think it can be closed. I will follow this up in vsc.
