### ISSUE TITLE
command to build/test all targets in the opened directory (package)

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/vscode-bazel#91]
Prior to this extension, we use custom tasks to build/test all bazel targets in the opened directory. Would like to have these commands provided by this extension.

```json
  "options": {
    "cwd": "${fileDirname}"
  },
  "tasks": [
    {
      "label": "Bazel: build :all",
      "group": {
        "kind": "build",
      },
      "command": "bazel build :all",
    },
    {
      "label": "Bazel: test :all",
      "group": {
        "kind": "test",
      },
      "command": "bazel test :all"
    },
  ],
```

**Comment by allevato** [comment]
This was added in #81, so it will be included in the next release.

**Comment by allevato** [comment]
That is, it's been added as a command in the context menu of tree view items. If you want something that does the same thing for the package containing the file currently being edited, that seems reasonable!

**Comment by ashi009** [comment]
Hey @allevato, may I ask when will be the next release take place?

**Comment by allevato** [comment]
The 0.2.0 release (May) contained this feature, so this should have been closed.
